# Generated by Django 4.1.7 on 2023-04-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('hitpoint', models.IntegerField(verbose_name='Hitpoint')),
                ('power_atеack', models.IntegerField(verbose_name='Power_attack')),
                ('armor', models.FloatField(verbose_name='Armor')),
                ('speed', models.FloatField(verbose_name='Speed')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=250, verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('url', models.CharField(max_length=100, verbose_name='Url')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('balance', models.FloatField(verbose_name='Balance')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
