# Generated by Django 4.1.7 on 2023-04-02 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionsdj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='power_atеack',
            new_name='power_attack',
        ),
    ]
